const characters = {
    cff: {
        name: 'cff',
        idles: "./arena/cffi.png",
        attack: "./arena/cffa.png",
        power: 7,
        defense: 4,
        hover: true,
    },
    cfs: {
        name: 'cfs',
        idles: "./arena/cfsi.png",
        attack: "./arena/cfsa.png",
        power: 8,
        defense: 4,
        hover: true,
    },
    cfc: {
        name: 'cfc',
        idles: "./arena/cfci.png",
        attack: "./arena/cfca.png",
        power: 9,
        defense: 4,
        hover: true,
    },
    csf: {
        name: 'csf',
        idles: "./arena/csfi.png",
        attack: "./arena/csfa.png",
        power: 7,
        defense: 5,
        hover: true,
    },
    css: {
        name: 'css',
        idles: "./arena/cssi.png",
        attack: "./arena/cssa.png",
        power: 8,
        defense: 5,
        hover: true,
    },
    csc: {
        name: 'csc',
        idles: "./arena/csci.png",
        attack: "./arena/csca.png",
        power: 9,
        defense: 5,
        hover: true,
    },
    crf: {
        name: 'crf',
        idles: "./arena/crfi.png",
        attack: "./arena/crfa.png",
        power: 7,
        defense: 6,
        hover: true,
    },
    crs: {
        name: 'crs',
        idles: "./arena/crsi.png",
        attack: "./arena/crsa.png",
        power: 8,
        defense: 6,
        hover: true,
    },
    crc: {
        name: 'crc',
        idles: "./arena/crci.png",
        attack: "./arena/crca.png",
        power: 9,
        defense: 6,
        hover: true,
    },
    hff: {
        name: 'hff',
        idles: "./arena/hffi.png",
        attack: "./arena/hffa.png",
        power: 8,
        defense: 4,
        hover: true,
    },
    hfs: {
        name: 'hfs',
        idles: "./arena/hfsi.png",
        attack: "./arena/hfsa.png",
        power: 9,
        defense: 4,
        hover: true,
    },
    hfc: {
        name: 'hfc',
        idles: "./arena/hfci.png",
        attack: "./arena/hfca.png",
        power: 10,
        defense: 4,
        hover: true,
    },
    hsf: {
        name: 'hsf',
        idles: "./arena/hsfi.png",
        attack: "./arena/hsfa.png",
        power: 8,
        defense: 5,
        hover: true,
    },
    hss: {
        name: 'hss',
        idles: "./arena/hssi.png",
        attack: "./arena/hssa.png",
        power: 9,
        defense: 5,
        hover: true,
    },
    hsc: {
        name: 'hsc',
        idles: "./arena/hsci.png",
        attack: "./arena/hsca.png",
        power: 10,
        defense: 5,
        hover: true,
    },
    hrf: {
        name: 'hrf',
        idles: "./arena/hrfi.png",
        attack: "./arena/hrfa.png",
        power: 8,
        defense: 6,
        hover: true,
    },
    hrs: {
        name: 'hrs',
        idles: "./arena/hrsi.png",
        attack: "./arena/hrsa.png",
        power: 9,
        defense: 6,
        hover: true,
    },
    hrc: {
        name: 'hrc',
        idles: "./arena/hrci.png",
        attack: "./arena/hrca.png",
        power: 10,
        defense: 6,
        hover: true,
    },
    lff: {
        name: 'lff',
        idles: "./arena/lffi.png",
        attack: "./arena/lffa.png",
        power: 9,
        defense: 4,
        hover: true,
    },
    lfs: {
        name: 'lfs',
        idles: "./arena/lfsi.png",
        attack: "./arena/lfsa.png",
        power: 10,
        defense: 4,
        hover: true,
    },
    lfc: {
        name: 'lfc',
        idles: "./arena/lfci.png",
        attack: "./arena/lfca.png",
        power: 11,
        defense: 4,
        hover: true,
    },
    lsf: {
        name: 'lsf',
        idles: "./arena/lsfi.png",
        attack: "./arena/lsfa.png",
        power: 9,
        defense: 5,
        hover: true,
    },
    lss: {
        name: 'lss',
        idles: "./arena/lssi.png",
        attack: "./arena/lssa.png",
        power: 10,
        defense: 5,
        hover: true,
    },
    lsc: {
        name: 'lsc',
        idles: "./arena/lsci.png",
        attack: "./arena/lsca.png",
        power: 11,
        defense: 5,
        hover: true,
    },
    lrf: {
        name: 'lrf',
        idles: "./arena/lrfi.png",
        attack: "./arena/lrfa.png",
        power: 9,
        defense: 6,
        hover: true,
    },
    lrs: {
        name: 'lrs',
        idles: "./arena/lrsi.png",
        attack: "./arena/lrsa.png",
        power: 10,
        defense: 6,
        hover: true,
    },
    lrc: {
        name: 'lrc',
        idles: "./arena/lrci.png",
        attack: "./arena/lrca.png",
        power: 11,
        defense: 6,
        hover: false,
    },
}