const characters = {
    cff: {
        name: 'cff',
        idles: "./arena/cffi.png",
        attack: "./arena/cffa.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    cfs: {
        name: 'cfs',
        idles: "./arena/cfsi.png",
        attack: "./arena/cfsa.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    cfc: {
        name: 'cfc',
        idles: "./arena/cfci.png",
        attack: "./arena/cfca.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    csf: {
        name: 'csf',
        idles: "./arena/csfi.png",
        attack: "./arena/csfa.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    css: {
        name: 'css',
        idles: "./arena/cssi.png",
        attack: "./arena/cssa.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    csc: {
        name: 'csc',
        idles: "./arena/csci.png",
        attack: "./arena/csca.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    crf: {
        name: 'crf',
        idles: "./arena/crfi.png",
        attack: "./arena/crfa.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    crs: {
        name: 'crs',
        idles: "./arena/crsi.png",
        attack: "./arena/crsa.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    crc: {
        name: 'crc',
        idles: "./arena/crci.png",
        attack: "./arena/crci.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chff: {
        name: 'chff',
        idles: "./arena/chffi.png",
        attack: "./arena/chffa.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chfs: {
        name: 'chfs',
        idles: "./arena/chfsi.png",
        attack: "./arena/chfsi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chfc: {
        name: 'chfc',
        idles: "./arena/chfci.png",
        attack: "./arena/chfci.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chsf: {
        name: 'chsf',
        idles: "./arena/chsfi.png",
        attack: "./arena/chsfi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chss: {
        name: 'chss',
        idles: "./arena/chssi.png",
        attack: "./arena/chssi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chsc: {
        name: 'chsc',
        idles: "./arena/chsci.png",
        attack: "./arena/chsci.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chrf: {
        name: 'chrf',
        idles: "./arena/chrfi.png",
        attack: "./arena/chrfi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chrs: {
        name: 'chrs',
        idles: "./arena/chrsi.png",
        attack: "./arena/chrsi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    chrc: {
        name: 'chrc',
        idles: "./arena/chrci.png",
        attack: "./arena/chrci.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lff: {
        name: 'lff',
        idles: "./arena/lffi.png",
        attack: "./arena/lffi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lfs: {
        name: 'lfs',
        idles: "./arena/lfsi.png",
        attack: "./arena/lfsi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lfc: {
        name: 'lfc',
        idles: "./arena/lfci.png",
        attack: "./arena/lfci.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lsf: {
        name: 'lsf',
        idles: "./arena/lsfi.png",
        attack: "./arena/lsfi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lss: {
        name: 'lss',
        idles: "./arena/lssi.png",
        attack: "./arena/lssi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lsc: {
        name: 'lsc',
        idles: "./arena/lsci.png",
        attack: "./arena/lsca.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lrf: {
        name: 'lrf',
        idles: "./arena/lrfi.png",
        attack: "./arena/lrfi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lrs: {
        name: 'lrs',
        idles: "./arena/lrsi.png",
        attack: "./arena/lrsi.png",
        power: 30,
        defense: 30,
        hover: true,
    },
    lrc: {
        name: 'lrc',
        idles: "./arena/lrci.png",
        attack: "./arena/lrci.png",
        power: 30,
        defense: 30,
        hover: false,
    },
}