const characters = {
    cff: {
        name: 'cff',
        idles: "./tarena/cffi.png",
        attack: "./tarena/cffa.png",
        power: 7,
        defense: 4,
        hover: true,
    },
    cfs: {
        name: 'cfs',
        idles: "./tarena/cfsi.png",
        attack: "./tarena/cfsa.png",
        power: 8,
        defense: 4,
        hover: true,
    },
    cfc: {
        name: 'cfc',
        idles: "./tarena/cfci.png",
        attack: "./tarena/cfca.png",
        power: 9,
        defense: 4,
        hover: true,
    },
    csf: {
        name: 'csf',
        idles: "./tarena/csfi.png",
        attack: "./tarena/csfa.png",
        power: 7,
        defense: 5,
        hover: true,
    },
    css: {
        name: 'css',
        idles: "./tarena/cssi.png",
        attack: "./tarena/cssa.png",
        power: 8,
        defense: 5,
        hover: true,
    },
    csc: {
        name: 'csc',
        idles: "./tarena/csci.png",
        attack: "./tarena/csca.png",
        power: 9,
        defense: 5,
        hover: true,
    },
    crf: {
        name: 'crf',
        idles: "./tarena/crfi.png",
        attack: "./tarena/crfa.png",
        power: 7,
        defense: 6,
        hover: true,
    },
    crs: {
        name: 'crs',
        idles: "./tarena/crsi.png",
        attack: "./tarena/crsa.png",
        power: 8,
        defense: 6,
        hover: true,
    },
    crc: {
        name: 'crc',
        idles: "./tarena/crci.png",
        attack: "./tarena/crca.png",
        power: 9,
        defense: 6,
        hover: true,
    },
    hff: {
        name: 'hff',
        idles: "./tarena/hffi.png",
        attack: "./tarena/hffa.png",
        power: 8,
        defense: 4,
        hover: true,
    },
    hfs: {
        name: 'hfs',
        idles: "./tarena/hfsi.png",
        attack: "./tarena/hfsa.png",
        power: 9,
        defense: 4,
        hover: true,
    },
    hfc: {
        name: 'hfc',
        idles: "./tarena/hfci.png",
        attack: "./tarena/hfca.png",
        power: 10,
        defense: 4,
        hover: true,
    },
    hsf: {
        name: 'hsf',
        idles: "./tarena/hsfi.png",
        attack: "./tarena/hsfa.png",
        power: 8,
        defense: 5,
        hover: true,
    },
    hss: {
        name: 'hss',
        idles: "./tarena/hssi.png",
        attack: "./tarena/hssa.png",
        power: 9,
        defense: 5,
        hover: true,
    },
    hsc: {
        name: 'hsc',
        idles: "./tarena/hsci.png",
        attack: "./tarena/hsca.png",
        power: 10,
        defense: 5,
        hover: true,
    },
    hrf: {
        name: 'hrf',
        idles: "./tarena/hrfi.png",
        attack: "./tarena/hrfa.png",
        power: 8,
        defense: 6,
        hover: true,
    },
    hrs: {
        name: 'hrs',
        idles: "./tarena/hrsi.png",
        attack: "./tarena/hrsa.png",
        power: 9,
        defense: 6,
        hover: true,
    },
    hrc: {
        name: 'hrc',
        idles: "./tarena/hrci.png",
        attack: "./tarena/hrca.png",
        power: 10,
        defense: 6,
        hover: true,
    },
    lff: {
        name: 'lff',
        idles: "./tarena/lffi.png",
        attack: "./tarena/lffa.png",
        power: 9,
        defense: 4,
        hover: true,
    },
    lfs: {
        name: 'lfs',
        idles: "./tarena/lfsi.png",
        attack: "./tarena/lfsa.png",
        power: 10,
        defense: 4,
        hover: true,
    },
    lfc: {
        name: 'lfc',
        idles: "./tarena/lfci.png",
        attack: "./tarena/lfca.png",
        power: 11,
        defense: 4,
        hover: true,
    },
    lsf: {
        name: 'lsf',
        idles: "./tarena/lsfi.png",
        attack: "./tarena/lsfa.png",
        power: 9,
        defense: 5,
        hover: true,
    },
    lss: {
        name: 'lss',
        idles: "./tarena/lssi.png",
        attack: "./tarena/lssa.png",
        power: 10,
        defense: 5,
        hover: true,
    },
    lsc: {
        name: 'lsc',
        idles: "./tarena/lsci.png",
        attack: "./tarena/lsca.png",
        power: 11,
        defense: 5,
        hover: true,
    },
    lrf: {
        name: 'lrf',
        idles: "./tarena/lrfi.png",
        attack: "./tarena/lrfa.png",
        power: 9,
        defense: 6,
        hover: true,
    },
    lrs: {
        name: 'lrs',
        idles: "./tarena/lrsi.png",
        attack: "./tarena/lrsa.png",
        power: 10,
        defense: 6,
        hover: true,
    },
    lrc: {
        name: 'lrc',
        idles: "./tarena/lrci.png",
        attack: "./tarena/lrca.png",
        power: 11,
        defense: 6,
        hover: false,
    },
}